[project]
name = "write-yourself-a-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
]

[project.scripts]
wyag = "libwyag.libwyag:main"
